--- Day 8: Treetop Tree House ---


The expedition comes across a peculiar patch of tall trees all planted carefully in a grid. The Elves explain that a previous expedition planted these trees as a reforestation effort. Now, they're curious if this would be a good location for a tree house.

First, determine whether there is enough tree cover here to keep a tree house hidden. To do this, you need to count the number of trees that are visible from outside the grid when looking directly along a row or column.

The Elves have already launched a quadcopter to generate a map with the height of each tree (your puzzle input). For example:

30373
25512
65332
33549
35390
Each tree is represented as a single digit whose value is its height, where 0 is the shortest and 9 is the tallest.

A tree is visible if all of the other trees between it and an edge of the grid are shorter than it. Only consider trees in the same row or column; that is, only look up, down, left, or right from any given tree.

All of the trees around the edge of the grid are visible - since they are already on the edge, there are no trees to block the view. In this example, that only leaves the interior nine trees to consider:

The top-left 5 is visible from the left and top. (It isn't visible from the right or bottom since other trees of height 5 are in the way.)
The top-middle 5 is visible from the top and right.
The top-right 1 is not visible from any direction; for it to be visible, there would need to only be trees of height 0 between it and an edge.
The left-middle 5 is visible, but only from the right.
The center 3 is not visible from any direction; for it to be visible, there would need to be only trees of at most height 2 between it and an edge.
The right-middle 3 is visible from the right.
In the bottom row, the middle 5 is visible, but the 3 and 4 are not.
With 16 trees visible on the edge and another 5 visible in the interior, a total of 21 trees are visible in this arrangement.

Consider your map; how many trees are visible from outside the grid?

In [71]:
with open("input8.txt") as f:
    text = f.read()
#print(text)

In [72]:
data = text.splitlines()
data2=[list(x) for x in data]
data2_int=[[int(float(j)) for j in i] for i in data2]

In [73]:
#print(len(data2_int))
import numpy as np
forest=np.array(data2_int)
print(forest)

[[0 1 2 ... 2 0 2]
 [1 0 2 ... 0 2 1]
 [2 2 2 ... 2 0 1]
 ...
 [0 0 1 ... 0 2 1]
 [2 1 2 ... 2 1 2]
 [1 1 0 ... 0 1 0]]


In [100]:
def visible(i,j, forest):
    if(i==0 or j==0 or i==forest.shape[0] or j==forest.shape[1]):
        #print("Tree visible")
        return True
    if((forest[i,j]>forest[:i,j]).all() or (forest[i,j]>forest[(i+1):,j]).all() or (forest[i,j]>forest[i,:j]).all() or (forest[i,j]>forest[i,(j+1):]).all()):
        #print("Tree visible")
        return True

In [101]:
trials=np.array([[3,0,3,7,3],[2,5,5,1,2],[6,5,3,3,2],[3,3,5,4,9],[3,5,3,9,0]],ndmin=2)
print(trials)

[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]


In [102]:
rows=forest.shape[0]
columns=forest.shape[1]
print(columns, rows)
vis_trees=0
for i in range(rows):
    for j in range(columns):
        #print(i,j)
        if(visible(i,j, forest)):
            vis_trees+=1
vis_trees

99 99


1825

In [104]:
vis_trees=0
rows=trials.shape[0]
columns=trials.shape[1]
for i in range(rows):
    for j in range(columns):
        if(visible(i,j, trials)):
            vis_trees+=1

vis_trees

21

--- Part Two ---


Content with the amount of tree cover available, the Elves just need to know the best spot to build their tree house: they would like to be able to see a lot of trees.

To measure the viewing distance from a given tree, look up, down, left, and right from that tree; stop if you reach an edge or at the first tree that is the same height or taller than the tree under consideration. (If a tree is right on the edge, at least one of its viewing distances will be zero.)

The Elves don't care about distant trees taller than those found by the rules above; the proposed tree house has large eaves to keep it dry, so they wouldn't be able to see higher than the tree house anyway.

In the example above, consider the middle 5 in the second row:

30373
25512
65332
33549
35390
Looking up, its view is not blocked; it can see 1 tree (of height 3).
Looking left, its view is blocked immediately; it can see only 1 tree (of height 5, right next to it).
Looking right, its view is not blocked; it can see 2 trees.
Looking down, its view is blocked eventually; it can see 2 trees (one of height 3, then the tree of height 5 that blocks its view).
A tree's scenic score is found by multiplying together its viewing distance in each of the four directions. For this tree, this is 4 (found by multiplying 1 * 1 * 2 * 2).

However, you can do even better: consider the tree of height 5 in the middle of the fourth row:

30373
25512
65332
33549
35390
Looking up, its view is blocked at 2 trees (by another tree with a height of 5).
Looking left, its view is not blocked; it can see 2 trees.
Looking down, its view is also not blocked; it can see 1 tree.
Looking right, its view is blocked at 2 trees (by a massive tree of height 9).
This tree's scenic score is 8 (2 * 2 * 1 * 2); this is the ideal spot for the tree house.

Consider each tree on your map. What is the highest scenic score possible for any tree?

In [246]:
trials

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [251]:
def viewing_score(i,j, forest):
    left=0
    right=0
    up=0
    down=0
    #if(forest.shape[1]>j):
     #   right+=1
    #if(j>0):
     #   left+=1
    #if(forest.shape[0]>i):
     #   down+=1
    #if(i>0):
     #   up+=1
    #print(up,left,down,right)
   
    for i2 in reversed(range(i)):
        #print("\n\n",i2)
        if(forest[i2,j]<forest[i,j]):
            up+=1
        else:
            #print(left)
            up+=1
            break
    for i3 in range(i+1,forest.shape[0]):
        #print("\n",i3)
        if(forest[i3,j]<forest[i,j]):
            down+=1
        else:
            #print(right)
            down+=1
            break
    for j2 in reversed(range(0,j)):
        #print("\n",j2)
        if(forest[i,j2]<forest[i,j]):
            #print("\n",i,j2)
            #print(forest[i,j2])
            left+=1
        else:
            left+=1
            #print(up)
            break
    for j3 in range(j+1,forest.shape[1]):
        #print("\n",j3)
        if(forest[i,j3]<forest[i,j]):
            right+=1
        else:
            #print(down)
            right+=1
            break
    #print(up,left,down,right)
    score=right*left*up*down        
    #print(score)
    return score

In [252]:
viewing_score(3,2,trials)

8

In [253]:
trials

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [256]:
#vis_trees=0
tree_score=np.zeros([rows, columns], dtype=int)
rows=trials.shape[0]
columns=trials.shape[1]
for i in range(rows):
    for j in range(columns):
        tree_score[i,j]=viewing_score(i,j,trials)
        

tree_score

array([[0, 0, 0, 0, 0],
       [0, 1, 4, 1, 0],
       [0, 6, 1, 2, 0],
       [0, 1, 8, 3, 0],
       [0, 0, 0, 0, 0]])

In [257]:
np.amax(tree_score)

8

In [259]:
#vis_trees=0
rows=forest.shape[0]
columns=forest.shape[1]
tree_score=np.zeros([rows, columns], dtype=int)

for i in range(rows):
    for j in range(columns):
        tree_score[i,j]=viewing_score(i,j,forest)
        

tree_score

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1, 14, ...,  1,  8,  0],
       [ 0, 12, 12, ...,  8,  1,  0],
       ...,
       [ 0,  1,  2, ...,  1,  8,  0],
       [ 0,  3,  8, ...,  8,  1,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [260]:
np.amax(tree_score)

235200